# Generated by Django 3.0.5 on 2020-07-01 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WannaEat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Nickname'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WannaEat.Receipt'),
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_parent_friends', to='WannaEat.User')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WannaEat.User')),
            ],
            options={
                'verbose_name': 'friend_list',
                'verbose_name_plural': 'friend_lists',
            },
        ),
    ]
