# Generated by Django 3.0.5 on 2020-07-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WannaEat', '0002_auto_20200701_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptboard',
            name='user',
        ),
        migrations.AddField(
            model_name='receiptboard',
            name='name',
            field=models.TextField(default='Name', verbose_name='Name'),
            preserve_default=False,
        ),
    ]
