# Generated by Django 3.0.5 on 2020-07-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WannaEat', '0004_receiptboard_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptboard',
            old_name='test',
            new_name='text',
        ),
    ]
