# Generated by Django 3.0.5 on 2020-09-22 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WannaEat', '0005_auto_20200726_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='product_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Receipt_list', to='WannaEat.ProductsList'),
        ),
    ]
